sudo: required
language: node_js
dist: trusty
node_js:
  - '9'
  - '8'
  - '6'
  - '5'
  - '4'
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq python build-essential make automake
